# Generated by Django 5.0.7 on 2024-07-20 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0021_rename_image_typemedition_image_off_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='days_for_interval',
            field=models.IntegerField(default=0, verbose_name='Dias por intervalo'),
        ),
        migrations.AddField(
            model_name='competence',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de fin'),
        ),
        migrations.AddField(
            model_name='competence',
            name='interval_quantity',
            field=models.IntegerField(default=0, verbose_name='intervalo'),
        ),
        migrations.AddField(
            model_name='competence',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='finalizado'),
        ),
        migrations.AddField(
            model_name='competence',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AddField(
            model_name='registeractivity',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='esta finalizado'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='address',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='phone',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='registeractivity',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='duración'),
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Fecha de modificacion.', verbose_name='modified at')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('is_finished', models.BooleanField(default=False, verbose_name='finalizado')),
                ('activities', models.ManyToManyField(to='move4it.activity', verbose_name='actividades')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move4it.competence', verbose_name='competencia')),
            ],
            options={
                'verbose_name': 'Intervalo',
                'verbose_name_plural': 'Intervalos',
            },
        ),
    ]
