# Generated by Django 5.0.7 on 2024-07-29 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0022_competence_days_for_interval_competence_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='fecha de inicio'),
            preserve_default=False,
        ),
    ]
