# Generated by Django 5.0.7 on 2024-07-29 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0023_alter_competence_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='competences',
        ),
        migrations.AddField(
            model_name='competence',
            name='enterprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='move4it.enterprise', verbose_name='empresa'),
            preserve_default=False,
        ),
    ]
