# Generated by Django 5.0.7 on 2024-07-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0024_remove_enterprise_competences_competence_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='generate_assignments',
            field=models.BooleanField(default=False, verbose_name='crear asignaciones'),
        ),
    ]
