# Generated by Django 5.0.7 on 2024-07-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0026_registeractivity_user_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeractivity',
            name='user_assigned',
        ),
    ]
