# Generated by Django 5.1 on 2024-09-05 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4it', '0028_remove_registeractivity_is_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeractivity',
            name='interval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='move4it.interval', verbose_name='intervalo'),
        ),
    ]
