# Generated by Django 5.1 on 2024-08-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_corporalmeditions_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification_number',
            field=models.CharField(max_length=80, unique=True, verbose_name='(rut o pasaporte)'),
        ),
    ]
