from .blogs import BlogModelSerializer
from .enterprises import CompetenceRetrieveSerializer, EnterpriseSerializer, GroupSerializer, CompetenceSerializer, GroupSerializerList
from .activities import ActivitySerializerForm, ActivitySerializer, ActivityCategorySerializer, RegisterActivitySerializer, FileRegisterActivitySerializer
