from .blogs import BlogModelSerializer
from .enterprises import EnterpriseSerializer, GroupSerializer, CompetenceSerializer, GroupSerializerList 
from .activities import ActivitySerializerForm, ActivitySerializer, ActivityCategorySerializer, RegisterActivitySerializer, FileRegisterActivitySerializer
