# Generated by Django 5.0.6 on 2024-07-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('move4ia', '0016_alter_registeractivity_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeractivity',
            name='duration',
        ),
    ]
