# Generated by Django 5.1.4 on 2025-01-10 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4ia', '0029_registeractivity_interval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='global_points',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='is_challenge',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='is_global',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='registeractivity',
            name='enterprises',
        ),
        migrations.RemoveField(
            model_name='registeractivity',
            name='finish_date_time',
        ),
        migrations.RemoveField(
            model_name='registeractivity',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registeractivity',
            name='is_global',
        ),
        migrations.RemoveField(
            model_name='registeractivity',
            name='is_group',
        ),
        migrations.RemoveField(
            model_name='registeractivity',
            name='is_user',
        ),
        migrations.RemoveField(
            model_name='registeractivity',
            name='start_date_time',
        ),
        migrations.RemoveField(
            model_name='registeractivity',
            name='users',
        ),
        migrations.AddField(
            model_name='registeractivity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move4ia.activitycategory', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duración'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type_stats',
            field=models.CharField(blank=True, choices=[('INCREMENTAL', 'incremental'), ('PORCENTAJE', 'porcentaje')], max_length=1200, null=True, verbose_name='tipo de estadísticas'),
        ),
    ]
