# Generated by Django 5.1.5 on 2025-01-23 04:25

import api.move4ia.models.registers_activity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move4ia', '0030_remove_activity_global_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeractivity',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.move4ia.models.registers_activity.RegisterActivity.user_directory_path),
        ),
    ]
