from .blogs import BlogModelSerializer
from .enterprises import CompetenceRankingSerializer,CompetenceRetrieveSerializer, EnterpriseSerializer, GroupSerializer, CompetenceSerializer, GroupSerializerList
from .activities import ActivitySerializerForm, ActivitySerializer, ActivityCategorySerializer
from .registers_activity import RegisterActivitySerializer, FileRegisterActivitySerializer
